### ISSUE TITLE
Unable to create a new session in Redis

### ISSUE THREAD

**Issue by brestows** [burnersk/Dancer2-Session-Redis#10]
Any attempt to use Redis as a session engine with this plugin yields the following error

```
Exception caught in 'core.app.before_request' filter: Hook error: Unable to create a new session: Incomplete Redis configuration: required is either 'server' or 'sock' at /usr/share/perl5/site_perl/Dancer2/Session/Redis.pm line 152.
 at /usr/share/perl5/site_perl/Dancer2/Core/App.pm line 453.
 at /usr/share/perl5/site_perl/Dancer2/Plugin.pm line 580.
 at /usr/share/perl5/site_perl/Dancer2/Core/Role/Hookable.pm line 115.

/usr/share/perl5/site_perl/Dancer2/Session/Redis.pm around line 152

147	  my ( $dsl, $session_id, $data ) = @_;
148	  my $key = sprintf $dsl->redis_key, $session_id;
149	  if ( my $serialization = $dsl->_serialization ) {
150	    $data = $serialization->encode($data);
151	  }
152	  $dsl->_redis->set( $key => $data );
153	  $dsl->_redis->expire( $key => $dsl->session_duration );
154	  return;
155	}
156	
157	# Delete session data.
```

My config
```

session: "Redis"
engines:
  session:
    YAML:
      session_dir: '/tmp/dancer-session'
    Redis:
      cookie_name: "session_id"
      cookie_duration: 10000
      session_duration: 10800
      is_secure: 0
      is_http_only: 0
      redis_reconnect: 60
      redis_every: 5000
      redis_server: "localhost:6379"
      redis_name: "krokotail"
      redis_serialization:
        # Use Sereal as serialization module:
        module: "Dancer2::Session::Redis::Serialization::Sereal"
        # Serialization module configuration:
        # Use snappy compression
        compression: "snappy"
```
