### ISSUE TITLE
Don't save data in session

### ISSUE THREAD

**Issue by brestows** [burnersk/Dancer2-Session-Redis#12]
my config:

```
session "Redis"
engines:
  template:
    template_toolkit:
      ENCODING: utf8
      start_tag: '<%'
      end_tag:   '%>'
  session:
    Redis:
      cookie_name: "kroko_cookies"
      cookie_duration: 10000
      session_duration: 10800
      is_secure: 1
      is_http_only: 1
      redis_reconnect: 60
      redis_every: 5000
      redis_server: "localhost:6379"
      redis_name: "krokotail"
```
my code:
```
any ['get','post'] => '/login' => sub {
    my $error_string;
    if (request->method() eq 'POST') {
        debug "POST LOGIN: ",param ('login');
        session authenticate => true;
        session user => param('login');
    }
    if (session('authenticate')){
        redirect '/';
    } else {
        template 'login',{
            'path'  => param('requested_path'),
            'error' => $error_string,
            'login' => true,
        };
    }
};
```

session  user is empty. What I doing wrong?
if set session a "YAML" and add setting for session::yaml it work
 My project https://github.com/brestows/krokotail.git
